# Generated by Django 4.2.18 on 2025-01-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startrack', '0002_album_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
    ]
