# Generated by Django 4.2.18 on 2025-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startrack', '0003_remove_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
